###
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "juanito peres2",
  "description": "Switch blue",
  "price": 99.99,
  "stock": 10
}

###
GET http://localhost:3000/api/products

###
GET http://localhost:3000/api/products/4e6719cb-e1fc-4790-8159-aec171530bba


###
PATCH http://localhost:3000/api/products/650098c4-52ab-4a61-8ac5-d96a8e556d34
Content-Type: application/json

{
  "name": "simon pepesas",
  "description": "Switch blue",
  "price": 990.99,
  "stock": 11
}

###
DELETE  http://localhost:3000/api/products/bf6a50b4-07d5-4438-8ea9-4c746b42cea2


###
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Laptop ThinkPad T14",
  "price": 1200.50,
  "stock": 10
}

###
PATCH http://localhost:3000/api/products/97c7960a-2a3f-4714-a30a-afbec016ffe2
Content-Type: application/json

{
  "price": 300.00,
  "stock": 7
}

###
GET http://localhost:3000/api/products/97c7960a-2a3f-4714-a30a-afbec016ffe2/history