###
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Teclado mecánico4",
  "description": "Switch blue",
  "price": 99.99,
  "stock": 10
}

###
GET http://localhost:3000/api/products

###
GET http://localhost:3000/api/products/ca0382f4-62b7-48a3-a78a-46298c0001cc